
package catatRumah;

import java.awt.Frame;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



public class dataRumah extends javax.swing.JPanel {

    DefaultTableModel model;
    public dataRumah() {
        
        initComponents();
        Object[] header = {"No.","","Nama Perumahan","Alamat","E-mail","Pengembang","tipe"};
        model = new DefaultTableModel(header,0 );
        tbl_rumah.setModel(model);
        tbl_rumah.getModel();
        tbl_rumah.setRowHeight(30);
        tbl_rumah.getColumnModel().getColumn(0).setMinWidth(100);
        tbl_rumah.getColumnModel().getColumn(0).setMaxWidth(100);
        tbl_rumah.getColumnModel().getColumn(1).setMinWidth(0);
        tbl_rumah.getColumnModel().getColumn(1).setMaxWidth(0);
        loadData("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtcari = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_tambahData = new javax.swing.JButton();
        btn_edit_data = new javax.swing.JButton();
        btn_hapusData = new javax.swing.JButton();
        brn_logout = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_rumah = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/catatRumah/images/icons8_Google_Web_Search_25px.png"))); // NOI18N

        btn_tambahData.setText("Tambah ");
        btn_tambahData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahDataActionPerformed(evt);
            }
        });

        btn_edit_data.setText("Edit");
        btn_edit_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_dataActionPerformed(evt);
            }
        });

        btn_hapusData.setText("Hapus");
        btn_hapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusDataActionPerformed(evt);
            }
        });

        brn_logout.setText("LOGOUT");
        brn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_tambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_edit_data, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn_hapusData, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(brn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(brn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_tambahData, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit_data, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_hapusData, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tbl_rumah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_rumah);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
       String key = txtcari.getText();
        if (key.isEmpty()) {
            loadData("");
        }else {
            loadData(key);
        }
    }//GEN-LAST:event_txtcariKeyReleased

    private void btn_hapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusDataActionPerformed
        int r = tbl_rumah.getSelectedRow();
            if (r != -1) {
                int id = Integer.parseInt(tbl_rumah.getValueAt(r, 1).toString());
                int pilih = JOptionPane.showConfirmDialog(this, "Apakah anda yakin ?", "konfirmasi", JOptionPane.YES_NO_OPTION);
                if (pilih == 0) {
                    try {
                        Connection c = koneksiDB.MySQL();
                        Statement st = c.createStatement();
                        String q = "DELETE FROM data WHERE id="+id+"";
                        st.executeUpdate(q);
                        loadData("");
                        JOptionPane.showMessageDialog(this, "data telah dihapus");
                        
                    } catch (HeadlessException | SQLException e) {
                        JOptionPane.showMessageDialog(this, e.getMessage());
                    }
                    
                }
                
               
        }
    }//GEN-LAST:event_btn_hapusDataActionPerformed

    private void btn_edit_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_dataActionPerformed
       int baris = tbl_rumah.getSelectedRow();
            if (baris !=-1) {
            int id = Integer.parseInt(tbl_rumah.getValueAt(baris, 1).toString());
            String nama = tbl_rumah.getValueAt(baris, 1).toString();
             Data d = new  Data();
           
            d.setId(id);
            d.setNama(nama);
            utama.addComp(new ubahData(d));
        }
    }//GEN-LAST:event_btn_edit_dataActionPerformed

    private void btn_tambahDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahDataActionPerformed
        utama.addComp(new tambahData());
    }//GEN-LAST:event_btn_tambahDataActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void brn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_logoutActionPerformed
         int pilih = JOptionPane.showConfirmDialog(this,
                    "Apakah anda yakin ingin keluar?",
                    "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
        if(pilih == JOptionPane.YES_OPTION){
            login l = new login();
            l.setExtendedState(Frame.MAXIMIZED_BOTH);
            this.setVisible(false);
            l.setVisible(true);
        }
    }//GEN-LAST:event_brn_logoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brn_logout;
    private javax.swing.JButton btn_edit_data;
    private javax.swing.JButton btn_hapusData;
    private javax.swing.JButton btn_tambahData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tbl_rumah;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
private void loadData(String key){
    try {
        model.setRowCount(0);
        Connection c = koneksiDB.MySQL();
        Statement st = c.createStatement();
        String where = key.isEmpty()? "":" WHERE namaRumah LIKE '%"+key+"%'";
        
        
        ResultSet rs = st.executeQuery("SELECT * FROM data"+where);
        int no = 0;
        while (rs.next()) {            
            no++;
            int id = rs.getInt("id");
                String nama = rs.getString("namaRumah");
                String alamat = rs.getString("alamat");
                String e_mail = rs.getString("email");
                String pengembang = rs.getString("pengembang");
                String tipe = rs.getString("tipe");
                Object[]  data = {no, id, nama, alamat, e_mail, pengembang, tipe};
                model.addRow(data);
        }
        
    } catch (SQLException e) {
    }
}

}

